Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
modile: Command not found.
Loading compiler version 2022.0.1
Loading tbb version 2021.5.0
Loading debugger version 2021.5.0
Loading compiler-rt version 2022.0.1
Loading dpl version 2021.6.0
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'inteloneapi/mpi/2022.0.1'
Loading compiler version 2022.0.1
Loading tbb version 2021.5.0
Loading debugger version 2021.5.0
Loading compiler-rt version 2022.0.1
Loading dpl version 2021.6.0
Loading mpi version 2021.5.0
Loading mkl version 2022.0.1
Loading compiler-rt version 2022.0.1
Loading tbb version 2021.5.0
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 9: setenv: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 15: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 16: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 17: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 18: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 19: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 20: modile: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 21: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 22: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 23: module: command not found
/var/lib/torque/mom_priv/jobs/575950.mgmt01.SC: line 24: module: command not found

Fri Jan 12 08:51:14 CET 2024

Job id: 575950.mgmt01

Directory: /scratch/bt307806/3D_Numerical_suites/Lukas_Initial_Setup/Python3D
Traceback (most recent call last):
  File "Slab_Break_off3D.py", line 66, in <module>
    _run_script_visualization(ptsave,Folder,L,l_,ptsave_DB,'Calibration')
  File "/scratch/bt307806/3D_Numerical_suites/Lukas_Initial_Setup/Python3D/Running_script_main_function.py", line 161, in _run_script_visualization
    BSPT._plot_passive_tracers(FSurf,C.x,C.y,time,ipic,ptsave,'T')
  File "/scratch/bt307806/3D_Numerical_suites/Lukas_Initial_Setup/Python3D/Slab_detachment.py", line 1531, in _plot_passive_tracers
    scat = ax0.scatter(self.x[ipic,:],self.y[ipic,:],self.z[ipic,:],10,buf,marker='p')
  File "/cluster/intel_2020_1/intelpython3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2362, in scatter
    depthshade=depthshade)
  File "/cluster/intel_2020_1/intelpython3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 577, in patch_collection_2d_to_3d
    col.set_3d_properties(zs, zdir)
  File "/cluster/intel_2020_1/intelpython3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 531, in set_3d_properties
    self._offsets3d = juggle_axes(xs, ys, np.atleast_1d(zs), zdir)
  File "/cluster/intel_2020_1/intelpython3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 798, in juggle_axes
    elif zdir[0] == '-':
TypeError: 'int' object is not subscriptable

================================
  START btrzx2 EPILOGUE SCRIPT
================================

User is 

Epilogue Args (normal):

Job ID:              575950.mgmt01
User ID:             bt307806
Group ID:            vo_bgi
Job name:            SBO
Session ID:          30248
Resourse list:       neednodes=1:ppn=16:compute8,nodes=1:ppn=16:compute8,walltime=100:00:00
Resource used:       cput=00:13:04,mem=26519100kb,vmem=34687852kb,walltime=00:02:40
Queue name:          long
Account string:      
Exit code:           575950.mgmt010

Epilogue session ID: 30472

Hostlist:            r03n30 

#Nodes:              1

-------------------
Single node section
-------------------

Remaining user PIDs
PID TTY TIME CMD
PIDs forked from session leader_

 => No remaining processes to clean up
 => Drop buffers

================================
   END btrzx2 EPILOGUE SCRIPT
================================
